### ISSUE TITLE
Please make Executable name something more appropriate

### ISSUE THREAD

**Issue by ayourk** [MiniMage7/Match3Solver#7]
https://github.com/MiniMage7/Match3Solver/blob/3c7b0e0071e765d91a63b352760b00dc4bb76f74/rust/Cargo.toml#L2

The string "rust" is the executable name.  Please change this to "match3solver-rust" or something like that.  Also, the file Cargo.lock can be deleted from Github as it is one of the locally automatically generated files that Cargo spits out.

**Comment by MiniMage7** [comment]
While yes, Cargo.lock is made by the compiler, as explained here https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html, it is recommended to be included in a git repository to create reproducible builds.

I will change the executable name in the next version though.
